### ISSUE TITLE
Installation instructions do not seem to work

### ISSUE THREAD

**Issue by JJ** [lino-levan/pyro#20]
This

https://github.com/lino-levan/pyro/blob/d47b22153caff78ca1cb6532fb716666d9f56e30/www/pages/index.md?plain=1#L27

Issues an error:

```
error: Could not find the config file: /home/jmerelo/Code/js/saco-js/https://deno.land/x/pyro/deno.jsonc
```

At least in Linux

**Comment by lino-levan** [comment]
I will take a look
