### ISSUE TITLE
Color flash on page reload

### ISSUE THREAD

**Issue by crowlsyong** [lino-levan/pyro#43]
While visiting [https://astral.deno.dev/](https://astral.deno.dev/), I get an orange flash when I click on buttons and page refreshes. I waited a bit and tried to reproduce and now it's a blue color that flashes when I click buttons. Sorry if this isn't the right place to put this. I appreciate what you're doin 🥰

**Comment by lino-levan** [comment]
Thanks for reporting, this is definitely the right place! I can't seem to reproduce on my end. What browser/OS are you on?

**Comment by crowlsyong** [comment]
I believe it was a problem with my system. I restarted and it is fixed. I attempted to reproduce on Firefox and Edge _before restart_ and I was unable to reproduce the issue on those browsers. 

[How it looked before restart](https://youtu.be/s10_B-b_oDM)

My system
About Chrome Version 116.0.5845.190 (Official Build) (64-bit)
Windows 11

**Comment by lino-levan** [comment]
Interesting. Thanks for sharing! Let me know if this comes up again!
