### ISSUE TITLE
sidebar not auto hidden on mobile

### ISSUE THREAD

**Issue by scarf005** [lino-levan/pyro#44]
![Screenshot_2023-11-09-07-20-24-014_org.mozilla.fenix.jpg](https://github.com/lino-levan/pyro/assets/54838975/c9c8f257-a058-4be4-b3d2-55347b834aec)

hello, lovely to have more SSG framework for deno. however, despite #36 being resolved, it seems like sidebars in [pyro.deno.dev](https://pyro.deno.dev/getting-started/installation/) is not mobile friendly. specifically, it hides half of page.

**Comment by lino-levan** [comment]
Thanks for the issue. I will work to resolve this soon.
